CREATE TABLE products (
    id INT AUTO_INCREMENT PRIMARY KEY,
    company_id INT NOT NULL,
    sku VARCHAR(100) NOT NULL COMMENT 'Stock Keeping Unit - unique product identifier',
    name VARCHAR(255) NOT NULL,
    description TEXT,
    category_id INT,
    unit_of_measure_id INT NOT NULL,
    product_type ENUM('RAW_MATERIAL', 'COMPONENT', 'FINISHED_GOOD', 'SERVICE') DEFAULT 'FINISHED_GOOD',
    has_bom BOOLEAN DEFAULT FALSE COMMENT 'Whether this product has a Bill of Materials',
    is_purchasable BOOLEAN DEFAULT TRUE COMMENT 'Can be purchased from suppliers',
    is_sellable BOOLEAN DEFAULT TRUE COMMENT 'Can be sold to customers',
    is_manufacturable BOOLEAN DEFAULT FALSE COMMENT 'Can be manufactured using BOM',
    cost_price DECIMAL(15,2) DEFAULT 0.00 COMMENT 'Standard cost price',
    selling_price DECIMAL(15,2) DEFAULT 0.00 COMMENT 'Standard selling price',
    min_stock_level DECIMAL(15,3) DEFAULT 0.000 COMMENT 'Minimum stock level for reorder alerts',
    max_stock_level DECIMAL(15,3) DEFAULT 0.000 COMMENT 'Maximum stock level',
    lead_time_days INT DEFAULT 0 COMMENT 'Lead time in days for procurement/production',
    weight DECIMAL(10,3) COMMENT 'Product weight',
    dimensions VARCHAR(100) COMMENT 'Product dimensions (LxWxH)',
    barcode VARCHAR(100) COMMENT 'Product barcode',
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by INT,
    updated_by INT,
    FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
    FOREIGN KEY (category_id) REFERENCES product_categories(id) ON DELETE SET NULL,
    FOREIGN KEY (unit_of_measure_id) REFERENCES units_of_measure(id),
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL,
    UNIQUE KEY unique_sku_company (sku, company_id),
    INDEX idx_product_type (product_type),
    INDEX idx_has_bom (has_bom),
    INDEX idx_active (is_active)
); 