// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"github.com/google/wire"
	"github.com/pna/management-app-backend/internal/bean/implement"
	"github.com/pna/management-app-backend/internal/controller"
	"github.com/pna/management-app-backend/internal/controller/http"
	"github.com/pna/management-app-backend/internal/controller/http/middleware"
	"github.com/pna/management-app-backend/internal/controller/http/v1"
	"github.com/pna/management-app-backend/internal/database"
	"github.com/pna/management-app-backend/internal/repository/implement"
	"github.com/pna/management-app-backend/internal/service/implement"
)

// Injectors from wire.go:

func InitializeContainer(db database.Db) *controller.ApiContainer {
	healthHandler := v1.NewHealthHandler(db)
	helloWorldRepository := repositoryimplement.NewHelloWorldRepository(db)
	passwordEncoder := beanimplement.NewBcryptPasswordEncoder()
	helloWorldService := serviceimplement.NewHelloWorldService(helloWorldRepository, passwordEncoder)
	helloWorldHandler := v1.NewHelloWorldHandler(helloWorldService)
	authMiddleware := middleware.NewAuthMiddleware()
	userRepository := repositoryimplement.NewUserRepository(db)
	userService := serviceimplement.NewUserService(userRepository, passwordEncoder)
	userHandler := v1.NewUserHandler(userService)
	productRepository := repositoryimplement.NewProductRepository(db)
	inventoryRepository := repositoryimplement.NewInventoryRepository(db)
	productCategoryRepository := repositoryimplement.NewProductCategoryRepository(db)
	unitOfMeasureRepository := repositoryimplement.NewUnitOfMeasureRepository(db)
	productBomRepository := repositoryimplement.NewProductBomRepository(db)
	unitOfWork := repositoryimplement.NewUnitOfWork(db)
	productImageRepository := repositoryimplement.NewProductImageRepository(db)
	s3Service := beanimplement.NewS3Service()
	productService := serviceimplement.NewProductService(productRepository, inventoryRepository, productCategoryRepository, unitOfMeasureRepository, productBomRepository, unitOfWork, productImageRepository, s3Service)
	productHandler := v1.NewProductHandler(productService)
	productBomService := serviceimplement.NewProductBomService(productBomRepository, productRepository, productCategoryRepository, unitOfMeasureRepository, unitOfWork)
	productBomHandler := v1.NewProductBomHandler(productBomService)
	productCategoryService := serviceimplement.NewProductCategoryService(productCategoryRepository)
	productCategoryHandler := v1.NewProductCategoryHandler(productCategoryService)
	unitOfMeasureService := serviceimplement.NewUnitOfMeasureService(unitOfMeasureRepository, unitOfWork)
	unitOfMeasureHandler := v1.NewUnitOfMeasureHandler(unitOfMeasureService)
	inventoryHistoryRepository := repositoryimplement.NewInventoryHistoryRepository(db)
	inventoryService := serviceimplement.NewInventoryService(inventoryRepository, inventoryHistoryRepository, userRepository, productRepository, unitOfWork)
	inventoryHandler := v1.NewInventoryHandler(inventoryService)
	inventoryHistoryService := serviceimplement.NewInventoryHistoryService(inventoryHistoryRepository)
	inventoryHistoryHandler := v1.NewInventoryHistoryHandler(inventoryHistoryService)
	inventoryReceiptRepository := repositoryimplement.NewInventoryReceiptRepository(db)
	inventoryReceiptItemRepository := repositoryimplement.NewInventoryReceiptItemRepository(db)
	inventoryReceiptService := serviceimplement.NewInventoryReceiptService(inventoryReceiptRepository, inventoryReceiptItemRepository, inventoryRepository, inventoryHistoryRepository, userRepository, productRepository, unitOfWork)
	inventoryReceiptHandler := v1.NewInventoryReceiptHandler(inventoryReceiptService)
	customerRepository := repositoryimplement.NewCustomerRepository(db)
	customerService := serviceimplement.NewCustomerService(customerRepository, unitOfWork)
	customerHandler := v1.NewCustomerHandler(customerService)
	statisticsService := serviceimplement.NewStatisticsService(productRepository, customerRepository, inventoryRepository)
	statisticsHandler := v1.NewStatisticsHandler(statisticsService)
	productImageService := serviceimplement.NewProductImageService(productImageRepository, unitOfWork, s3Service)
	productImageHandler := v1.NewProductImageHandler(productImageService)
	orderRepository := repositoryimplement.NewOrderRepository(db)
	orderItemRepository := repositoryimplement.NewOrderItemRepository(db)
	orderImageRepository := repositoryimplement.NewOrderImageRepository(db)
	orderService := serviceimplement.NewOrderService(orderRepository, inventoryRepository, inventoryHistoryRepository, orderItemRepository, productRepository, productBomRepository, unitOfWork, userRepository, orderImageRepository, s3Service, customerRepository, unitOfMeasureRepository)
	orderHandler := v1.NewOrderHandler(orderService)
	server := http.NewServer(healthHandler, helloWorldHandler, authMiddleware, userHandler, productHandler, productBomHandler, productCategoryHandler, unitOfMeasureHandler, inventoryHandler, inventoryHistoryHandler, inventoryReceiptHandler, customerHandler, statisticsHandler, productImageHandler, orderHandler)
	apiContainer := controller.NewApiContainer(server)
	return apiContainer
}

// wire.go:

var container = wire.NewSet(controller.NewApiContainer)

// may have grpc server in the future
var serverSet = wire.NewSet(http.NewServer)

// handler === controller | with service and repository layers to form 3 layers architecture
var handlerSet = wire.NewSet(v1.NewHealthHandler, v1.NewHelloWorldHandler, v1.NewUserHandler, v1.NewProductHandler, v1.NewProductBomHandler, v1.NewProductCategoryHandler, v1.NewUnitOfMeasureHandler, v1.NewInventoryHandler, v1.NewInventoryHistoryHandler, v1.NewCustomerHandler, v1.NewStatisticsHandler, v1.NewInventoryReceiptHandler, v1.NewProductImageHandler, v1.NewOrderHandler)

var serviceSet = wire.NewSet(serviceimplement.NewHelloWorldService, serviceimplement.NewUserService, serviceimplement.NewProductService, serviceimplement.NewInventoryService, serviceimplement.NewInventoryHistoryService, serviceimplement.NewCustomerService, serviceimplement.NewStatisticsService, serviceimplement.NewUnitOfMeasureService, serviceimplement.NewProductCategoryService, serviceimplement.NewProductImageService, serviceimplement.NewProductBomService, serviceimplement.NewInventoryReceiptService, serviceimplement.NewOrderService, serviceimplement.NewOrderImageService)

var repositorySet = wire.NewSet(repositoryimplement.NewHelloWorldRepository, repositoryimplement.NewUserRepository, repositoryimplement.NewProductRepository, repositoryimplement.NewInventoryRepository, repositoryimplement.NewInventoryHistoryRepository, repositoryimplement.NewUnitOfWork, repositoryimplement.NewCustomerRepository, repositoryimplement.NewUnitOfMeasureRepository, repositoryimplement.NewProductCategoryRepository, repositoryimplement.NewProductImageRepository, repositoryimplement.NewProductBomRepository, repositoryimplement.NewInventoryReceiptRepository, repositoryimplement.NewInventoryReceiptItemRepository, repositoryimplement.NewOrderRepository, repositoryimplement.NewOrderItemRepository, repositoryimplement.NewOrderImageRepository)

var middlewareSet = wire.NewSet(middleware.NewAuthMiddleware)

var beanSet = wire.NewSet(beanimplement.NewBcryptPasswordEncoder, beanimplement.NewS3Service)
